src/scraper_ui/contacts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("collectors/", views.collectors, name="collectors"),
    path("collectors/toggle", views.collector_toggle, name="collector_toggle"),
    path("contacts/", views.ContactListView.as_view(), name="contacts")
]

src/scraper_ui/members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login-user/', views.login_user, name="login"),
    path('register-user/', views.register_user, name="register"),
    path('logout-user/', views.logout_user, name="logout")
]

src/scraper_ui/scraper_ui/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contacts.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

src/scraper_ui/contacts/models.py
from django.db import models
from members.models import User
from .validators import validate_fqdn
from django.dispatch import receiver
from django.db.models.signals import post_save
from scraper.services import scrape_web_site


class WebSite(models.Model):
    domain = models.CharField(max_length=255, validators=[validate_fqdn])
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField("date added", auto_now_add=True)

    class Meta:
        unique_together = ('domain', 'owner')


class Collector(models.Model):
    code = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    active = models.BooleanField()

    class Meta:
        unique_together = ('code', 'owner',)


class Contact(models.Model):
    site = models.ForeignKey(WebSite, on_delete=models.CASCADE)
    collector = models.ForeignKey(Collector, on_delete=models.CASCADE)
    type = models.CharField(max_length=255)
    value = models.CharField(max_length=255)
    context = models.JSONField()

@receiver(post_save, sender=WebSite)
def website_created(sender, **kwargs):
    if kwargs['created']:
        scrape_web_site(kwargs['instance'])

src/scraper_ui/members/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.db.models.signals import post_save
from contacts.services import init_collectors


class User(AbstractUser):
    USERNAME_FIELD = 'username'
    pass

@receiver(post_save, sender=User)
def user_collectors(sender, **kwargs):
    if kwargs['created']:
        init_collectors(kwargs['instance'])

src/scraper_ui/contacts/forms.py
from django.forms import ModelForm
from .models import WebSite
from .validators import validate_fqdn
from django.core.exceptions import ValidationError


class WebSiteForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.owner = None
        self.fields['domain'].validators.append(validate_fqdn)
        self.fields['domain'].validators.append(self.validate_uniq)
        self.fields['domain'].widget.attrs = {
            'class': 'form-control',
            'placeholder': 'Please, enter your domain name'
        }

    class Meta:
        model = WebSite
        fields = ['domain']

    def set_owner(self, owner):
        self.owner = owner

    def validate_uniq(self, domain):
        try:
            WebSite.objects.get(domain=domain, owner=self.owner)
        except WebSite.DoesNotExist:
            pass
        else:
            raise ValidationError('WebSite already exists')

    def clean(self):
        cleaned_data = super().clean()



        return cleaned_data

src/scraper_ui/members/forms.py
from django import forms
from .models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for fld in self.fields:
            self.fields[fld].widget.attrs = {
                'class': 'form-control'
            }

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

src/scraper_ui/contacts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import WebSiteForm
from .models import Collector, Contact
from django.views.generic import ListView


@login_required(login_url='/members/login-user')
def dashboard(request):
    form = WebSiteForm(request.POST or None)
    if request.method == 'POST':
        form.set_owner(request.user)
        if form.is_valid():
            site = form.save(commit=False)
            site.owner = request.user
            site.save()
            messages.add_message(request, messages.INFO, "Website added successfully")
            redirect('dashboard')


    context = {'form': form}
    return render(request, "dashboard.html", context)

def collectors(request):
    own_collectors = Collector.objects.filter(owner=request.user)
    context = {'collectors': own_collectors}
    return render(request, "collectors.html", context)

def collector_toggle(request):
    if request.method == "POST":
        data = request.POST
        collector = Collector.objects.get(owner=request.user, pk=data.get('id'))
        collector.active ^= 1
        collector.save()
        return redirect('collectors')

class ContactListView(ListView):
    paginate_by = 20
    model = Contact
    ordering = ['-id']

    def get_queryset(self):
        return Contact.objects.filter(site__owner=self.request.user)

src/scraper_ui/members/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import RegisterForm


def register_user(request):
    form = RegisterForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, "Successful registration")
            return redirect('login')
    context = {'form': form}
    return render(request, 'auth/register.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Login success")
            return redirect('dashboard')
        else:
            messages.error(request, "Invalid credentials!")
            return redirect('login')
    elif request.user.is_authenticated:
        return redirect('dashboard')
    else:
        return render(request, 'auth/login.html')

def logout_user(request):
    logout(request)
    return redirect('login')

src/scraper_ui/contacts/templates/collectors.html
{% extends 'base.html' %}

{% block title %}Add site{% endblock %}

{% block content %}
<h1 class="heading">Collectors</h1>
<table class="table">
    <thead>
    <tr>
      <th scope="col">Collector Name</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
    {% for collector in collectors %}
    <tr>
        <td>{{ collector.code }}</td>
        <td>{{ collector.active|yesno:"ACTIVE,INACTIVE" }}</td>
        <td>
            <form method="POST" action="{% url 'collector_toggle' %}">
                {% csrf_token %}
                <input type="hidden" value="{{ collector.id }}" name="id" />
                <button type="submit" class="btn btn-outline-{{ collector.active|yesno:"danger,success" }}">{{ collector.active|yesno:"disable,enable" }}</button>
            </form>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

src/scraper_ui/contacts/templates/contacts/contact_list.html
{% extends 'base.html' %}

{% block title %}Add site{% endblock %}

{% block content %}
<h1 class="heading">Contacts</h1>
<table class="table">
    <thead>
    <tr>
        <th scope="col">Site</th>
        <th scope="col">Contact Type</th>
        <th scope="col">Contact</th>
        <th scope="col">Source</th>
    </tr>
    </thead>
    <tbody>
    {% for contact in page_obj %}
        <tr>
          <td>{{ contact.site.domain }}</td>
          <td>{{ contact.type }}</td>
          <td>{{ contact.value }}</td>
          <td>{{ contact.collector.code }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
    {% endif %}
    <li class="current page-item p-2">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </li>
    {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endblock %}

src/scraper_ui/contacts/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}Add site{% endblock %}

{% block content %}
<h1 class="heading">Add site</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_domain">Add site</label>
        {{ form.domain }}
        {{ form.domain.errors }}
    </div>
    <button type="submit" class="btn btn-primary mt-3">Add & Collect</button>
</form>
{% endblock %}

src/scraper_ui/scraper_ui/templates/base.html
<!DOCTYPE html>
<html lang="en" class="h-100">
<head>
    <link rel="stylesheet" href="style.css">
    <title>{% block title %}Change it please!{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</head>

<body class="h-100">
    <div class="d-flex flex-row m-4 h-100">
        {% if user.is_authenticated %}
        <aside class="px-4">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'dashboard' %}">Add site</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'contacts' %}">All Contacts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'collectors' %}">Collectors</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            </ul>
        </aside>
        <div class="border border-primary h-75"></div>
        {% endif %}
        <main class="container" id="content">
            {% if messages %}
            <ul class="list-group list-group-flush">
                {% for message in messages %}
                <li class="list-group-item">
                    <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            {% block content %}{% endblock %}
        </main>
    </div>
    {% block javascript %}{% endblock %}
</body>
</html>